<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>577631e8-f2fd-4ec7-9b97-5a9f62cc410d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/section/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;الملفات icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>811f75b5-08a6-40c8-ac78-69ac2cc6e311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> tw-relative tw-flex tw-transform tw-cursor-pointer tw-flex-col tw-items-center tw-justify-center tw-gap-4 tw-rounded-xl tw-bg-[#fff] tw-p-4 tw-transition-all tw-duration-300 tw-ease-in-out hover:tw-scale-105 hover:!tw-shadow-lg </value>
      <webElementGuid>1bf36c88-8200-450e-bfc0-871b645e5e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/files/category/tawjihi-2007</value>
      <webElementGuid>69ec09b1-8800-48de-b3f4-d11bcc618d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الملفات</value>
      <webElementGuid>686f3993-d327-4dc6-89bc-03250a046287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-center tw-justify-center tw-gap-12 tw-bg-[#F9F9F9] tw-p-2 md:!tw-p-5 lg:!tw-p-10&quot;]/div[@class=&quot;tw-grid tw-w-full tw-grid-cols-2 tw-gap-4 md:tw-grid-cols-3 lg:tw-grid-cols-4&quot;]/a[@class=&quot;tw-relative tw-flex tw-transform tw-cursor-pointer tw-flex-col tw-items-center tw-justify-center tw-gap-4 tw-rounded-xl tw-bg-[#fff] tw-p-4 tw-transition-all tw-duration-300 tw-ease-in-out hover:tw-scale-105 hover:!tw-shadow-lg&quot;]</value>
      <webElementGuid>2699ae8f-2e44-4786-a6ae-48b8095ba64e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/section/div[2]/a[3]</value>
      <webElementGuid>d9f208ef-eed2-4ea2-8477-faad028363e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تكميلي 2006'])[1]/following::a[3]</value>
      <webElementGuid>7f39349c-2282-4043-aa87-3892f99854bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='توجيهي 2009'])[1]/following::a[3]</value>
      <webElementGuid>c8c40cdc-a18b-4e75-98a5-0d54c433df47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمات جو اكاديمي ل جيل 2007'])[1]/preceding::a[9]</value>
      <webElementGuid>a1ff0751-847f-4bad-842f-fee2fb75dd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الساعات المكتبية 2007'])[1]/preceding::a[9]</value>
      <webElementGuid>c51d60ea-19f8-4ebe-b868-0c65576349e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/files/category/tawjihi-2007')]</value>
      <webElementGuid>b522b5a0-146b-490d-80de-81e19f7350e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]</value>
      <webElementGuid>36cb939c-305d-4786-b92f-ad3e966551c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/files/category/tawjihi-2007' and (text() = 'الملفات' or . = 'الملفات')]</value>
      <webElementGuid>acd1d9e7-3635-4968-82cf-5a22d32c88e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
