<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-close-line tw-text-center tw-text-30p_6befe3</name>
   <tag></tag>
   <elementGuidId>00fbeef9-2183-4c57-bd0e-c8e7eda17a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Close&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c5054918-7616-4c22-a90e-88cee7ce56f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-line tw-text-center tw-text-[30px] tw-leading-none tw-text-[#1A428A]</value>
      <webElementGuid>d35aea7a-9556-4724-b667-cf8339b47d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:re:&quot;)/button[@class=&quot;focus:tw-ring-ring data-[state=open]:tw-bg-accent data-[state=open]:tw-text-muted-foreground tw-absolute tw-end-4 tw-top-4 tw-z-10 tw-m-auto tw-flex tw-h-[35px] tw-h-[45px] tw-w-[35px] tw-w-[45px] tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-bg-white tw-leading-none tw-shadow tw-transition tw-duration-150 tw-ease-in-out hover:tw-bg-[#efefef] focus:tw-outline-none focus:tw-ring-2 focus:tw-ring-offset-2 disabled:tw-pointer-events-none&quot;]/i[@class=&quot;ri-close-line tw-text-center tw-text-[30px] tw-leading-none tw-text-[#1A428A]&quot;]</value>
      <webElementGuid>acd8b62c-f890-455a-bfcd-8b3ab22aafe4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:re:']/button/i</value>
      <webElementGuid>7b1b2185-8ee0-4c4a-893d-68978a2610d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/i</value>
      <webElementGuid>6d333aa2-cb28-4fd3-b312-7487a77b4326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
