<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-heart-line</name>
   <tag></tag>
   <elementGuidId>684664ae-1565-4964-9f20-135c73ebfbc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-heart-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/div[2]/div[2]/div[2]/div/div[2]/div[1]/div/div[2]/div[1]/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2c4d4e20-a354-46b0-a99f-dc0a12ac04c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-heart-line</value>
      <webElementGuid>f5df916e-6e03-498d-890a-8849de5a75a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-px-4 md:tw-px-[30px] lg:tw-px-[40px] 2xl:tw-px-[100px] tw-w-full !tw-overflow-hidden&quot;]/div[1]/div[@class=&quot;tw-flex tw-flex-col tw-gap-8&quot;]/div[@class=&quot;tw-rounded-lg tw-p-10&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-justify-between tw-gap-20 sm:tw-gap-4 md:tw-flex-row&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-4 tw-px-14 max-sm:tw-px-4&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-gap-2&quot;]/button[@class=&quot;tw-bg-primary tw-flex tw-w-full tw-items-center tw-justify-center tw-gap-4 tw-rounded-lg tw-bg-[#034173] tw-p-3 tw-text-[18px] tw-font-bold tw-text-white max-sm:tw-text-[14px]&quot;]/i[@class=&quot;ri-heart-line&quot;]</value>
      <webElementGuid>ce9452db-8e15-409a-9aa6-c12807df92cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div/div/div[2]/div/div/div[2]/div/button[2]/i</value>
      <webElementGuid>3b7e92b9-7a94-4dcb-b46c-c086cf61cc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>8b90cf7f-22ab-4272-8f6e-6d53e8a57eeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
