<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>813fd513-b6e3-403f-95ca-92b157f99c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>5c3d15d2-b7ef-4006-a656-58fb4308d0c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px] </value>
      <webElementGuid>4d207b92-cd46-43af-b5b4-ef780ef482d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي</value>
      <webElementGuid>65be256c-29a4-4cbe-be06-ebb806aa43a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/h2[@class=&quot;semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px]&quot;]</value>
      <webElementGuid>550219d0-984c-4fb9-aa1d-4e478322925f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      <webElementGuid>15bde1b6-8706-4894-bd5e-e85a9d7949d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر البرنامج الذي تفضل التصفح عبره، حتى تمكننا من خدمتك بأفضل طريقة ممكنة'])[1]/following::h2[1]</value>
      <webElementGuid>36de5757-241f-4bbc-92f2-c1f8eca10ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جو اكاديمي | جيل عربي متمكن'])[1]/following::h2[2]</value>
      <webElementGuid>5f193dbe-9a2b-4c6c-8fe2-52cf4bf5d88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الجامعات و الكليات'])[1]/preceding::h2[1]</value>
      <webElementGuid>3b218ff9-d089-4e71-a6eb-af758e77b2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الصفوف الاساسية'])[1]/preceding::h2[2]</value>
      <webElementGuid>857dfc3e-6496-423d-9061-7141de9889c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='برنامج التوجيهي و الثانوي']/parent::*</value>
      <webElementGuid>e71ebe9b-a928-4736-9c62-f976a6d3667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/h2</value>
      <webElementGuid>89a8a24a-b0cd-4dbd-9892-18eb75b3a07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'برنامج التوجيهي و الثانوي' or . = 'برنامج التوجيهي و الثانوي')]</value>
      <webElementGuid>be30267d-0fe4-4dde-8a89-d33454c08526</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
