<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1_2</name>
   <tag></tag>
   <elementGuidId>b2bed9c0-25a9-40e8-aa56-ba7ce4e8a626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/section/div/div/div[3]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;منشوراتي&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45464722-8deb-4302-98e3-7b381ab9d52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-pb-4</value>
      <webElementGuid>46e3d804-5312-4f77-8936-141b18213d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>منشوراتي</value>
      <webElementGuid>054af0c2-62e7-430a-a406-353be6c8790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-my-[80px] tw-w-full&quot;]/div[@class=&quot;tw-mt-[64px] tw-px-[10px] lg:tw-px-[40px] xl:tw-px-[120px]  tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-between tw-gap-[24px]  md:tw-flex-row&quot;]/section[@class=&quot;tw-flex tw-w-full tw-shrink-0 tw-flex-col tw-items-start tw-justify-start tw-gap-[24px] lg:!tw-w-2/3&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center&quot;]/div[@class=&quot;tw-mb-[42px] tw-w-full&quot;]/button[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-center tw-gap-[16px] tw-font-bold tw-transition tw-ease-in-out tw-duration-150 tw-bg-white tw-text-[20px] tw-border-b-[3px] tw-border-b-[#D8E6FF] tw-border-solid tw-text-[#1a418a7e]&quot;]/span[@class=&quot;tw-pb-4&quot;]</value>
      <webElementGuid>3b03f456-cbbb-427e-84cb-eb008b663883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/section/div/div/div[3]/button/span</value>
      <webElementGuid>194b2762-b572-4826-8253-a4bcc0241ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جروبات'])[1]/following::span[1]</value>
      <webElementGuid>0ea5ad08-a83d-4bb3-aab2-2a085c12e643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='منشورات'])[1]/following::span[2]</value>
      <webElementGuid>acfe5dfc-181d-4e9a-b32f-a3b0a7547057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشر'])[1]/preceding::span[2]</value>
      <webElementGuid>3d672964-fb00-419d-aabe-cf675a0a1a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='..Fa ti ma..'])[1]/preceding::span[2]</value>
      <webElementGuid>51dc2fac-11a3-4888-b85e-aa2d87d67b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='منشوراتي']/parent::*</value>
      <webElementGuid>f4f0d4a9-8c3b-4366-9309-e8c98e923dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>73d82f30-08c2-449a-99e9-3a56a7550d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'منشوراتي' or . = 'منشوراتي')]</value>
      <webElementGuid>b6017545-5ae5-42b6-b6ac-c7043d2bff67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
