<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_j</name>
   <tag></tag>
   <elementGuidId>b8b3f369-be49-4d0a-979a-0cb2118f9ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='description'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;ماذا يخطر في بالك ؟&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>15d14697-963b-410c-88f4-1ba5caaeb97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>9e64261a-72b9-4ef4-a878-7d085c89ee5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-h-auto tw-min-h-8 tw-w-full tw-resize-none tw-overflow-auto tw-rounded-xl tw-border tw-border-gray-100 tw-outline-none placeholder:tw-text-[#979797]</value>
      <webElementGuid>2901f460-1a66-4e8d-ab8c-c70918da771f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>2782337b-3bac-4b8a-92b9-f4771296d1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e3e2cb35-2a51-47ec-b32b-3793629d3d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>j</value>
      <webElementGuid>d3c9a794-76e7-4905-9688-2363c2a0219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r30:&quot;)/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-start tw-gap-[12px] tw-px-5&quot;]/div[@class=&quot;tw-h-full tw-w-full&quot;]/textarea[@id=&quot;description&quot;]</value>
      <webElementGuid>f5d63892-9fe4-4757-afc0-b3bf9c9cbfd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='description'])[2]</value>
      <webElementGuid>aa2fe645-35d5-4475-9c45-b6ccd260a9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r30:']/div/div[2]/textarea</value>
      <webElementGuid>c4882aaa-1af4-43d5-8d34-a7b424494cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohannad qa qa'])[3]/following::textarea[1]</value>
      <webElementGuid>db80d1a2-7048-4892-a77b-985b7bd0acce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل التعليق'])[1]/following::textarea[1]</value>
      <webElementGuid>d3573540-1269-4fef-99d7-4ee45b699f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ التعديل'])[1]/preceding::textarea[1]</value>
      <webElementGuid>af8494f7-a11e-46e4-bbce-82f1e51617ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::textarea[1]</value>
      <webElementGuid>b9133171-4f5a-4550-8fd9-f9ea720fee08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='j']/parent::*</value>
      <webElementGuid>ffacf508-56c9-4dd1-bcf6-e713ec73b93d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>ccc9cc46-f348-4303-bace-78588fb20a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'description' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'j' or . = 'j')]</value>
      <webElementGuid>e4b39e3e-6ae0-4709-a9d6-e839879ec5da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
