<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__ri-arrow-drop-down-line bold tw-text-2xl</name>
   <tag></tag>
   <elementGuidId>81993db9-861e-42b0-81d1-1e72a5ea6016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ri-arrow-drop-down-line.bold.tw-text-2xl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='radix-:r0:']/span/span[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;برنامج التوجيهي &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e972af2f-859b-4853-9797-23208523e1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-drop-down-line bold tw-text-2xl</value>
      <webElementGuid>df4a57d6-b889-44e1-bba2-dd1016bcee0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r0:&quot;)/span[@class=&quot;tw-flex tw-w-full !tw-flex-nowrap tw-items-center tw-justify-center tw-whitespace-nowrap tw-rounded-[14px] tw-bg-[#f2a057] tw-px-2 tw-py-1 tw-text-center tw-text-[1vw] tw-text-white hover:tw-bg-[#f4b780] xl:tw-text-base&quot;]/span[2]/i[@class=&quot;ri-arrow-drop-down-line bold tw-text-2xl&quot;]</value>
      <webElementGuid>fd57ddfd-4ca4-411d-a203-63c925855335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='radix-:r0:']/span/span[2]/i</value>
      <webElementGuid>d3fe522a-9878-4709-b654-1d5958f93412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/i</value>
      <webElementGuid>8678c07a-dac1-4ad7-a233-ce81e26d1317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
