<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit</name>
   <tag></tag>
   <elementGuidId>bd3cadb6-e7b5-43a7-82d1-774521622009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;تعديل&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r19:']/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;تعديل تعديل&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9425460a-7af0-4921-8db3-2553f31269cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>تعديل</value>
      <webElementGuid>7dc35b59-3906-4286-a596-ca2415abecef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>869d3adf-8d17-49c8-a527-9546c61888cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c067ea0b-3295-489e-9696-5e10122f88d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>e9bbfd72-e3da-411a-b1b9-d7887562dea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>ec113e6e-3120-419b-bd22-50840f2310c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cb732b9a-0da6-413b-ae07-8a6cbfa42439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/shababeek/edit.svg</value>
      <webElementGuid>a2dd8c6b-4bed-4375-a3ae-bfd481de203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r19:&quot;)/div[@class=&quot;tw-relative tw-flex tw-cursor-default tw-select-none tw-items-center tw-rounded-sm tw-px-2 tw-py-1.5 tw-text-sm tw-outline-none tw-transition-colors focus:tw-bg-slate-100 focus:tw-text-slate-900 data-[disabled]:tw-pointer-events-none data-[disabled]:tw-opacity-50 dark:focus:tw-bg-slate-800 dark:focus:tw-text-slate-50&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantGhost__8YgBv styles_buttonColorBlue__0VHnR tw-rounded-full tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] tw-flex tw-w-full tw-min-w-[80px] !tw-justify-start tw-gap-3 tw-rounded-none !tw-text-black&quot;]/img[1]</value>
      <webElementGuid>3f185aa6-8063-4a7b-a3b5-bbef66604f3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r19:']/div/button/img</value>
      <webElementGuid>dd29466e-264f-4086-b2c9-4de1898f485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='تعديل']</value>
      <webElementGuid>3711d244-1e95-4a44-8437-592b8152b8e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/img</value>
      <webElementGuid>17ae9304-e8d2-42c3-995e-b5447c8f283a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'تعديل' and @src = '/icons/shababeek/edit.svg']</value>
      <webElementGuid>492d61bb-012b-4e1b-8c7f-79e566513ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
