<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>41ce1c12-75a3-4ca5-af7e-f97425778ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>616e3bcc-7b21-4e46-b41b-6420ce696211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px] </value>
      <webElementGuid>f7f2e5b3-09b9-444a-a862-d409230159b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي</value>
      <webElementGuid>44a32e1f-d805-41e4-a2c9-a1059e5eaf7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/h2[@class=&quot;semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px]&quot;]</value>
      <webElementGuid>e7f0aa36-adac-4189-9f7f-f6b920465d32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      <webElementGuid>3b264ed2-ba14-4151-89df-4369dd6fc69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر البرنامج الذي تفضل التصفح عبره، حتى تمكننا من خدمتك بأفضل طريقة ممكنة'])[1]/following::h2[1]</value>
      <webElementGuid>afba5ba8-34c9-4fce-a723-9f1a83ab947b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جو اكاديمي | جيل عربي متمكن'])[1]/following::h2[2]</value>
      <webElementGuid>dcc79d00-0c3f-4218-958c-4e4624b0f68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الجامعات و الكليات'])[1]/preceding::h2[1]</value>
      <webElementGuid>9ebbe8ad-21e3-4391-82d0-dd32f7861ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الصفوف الاساسية'])[1]/preceding::h2[2]</value>
      <webElementGuid>2a7ff9ea-6791-4ae2-a960-2295bda4982b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='برنامج التوجيهي و الثانوي']/parent::*</value>
      <webElementGuid>28405053-94f5-49f4-b5a4-b683dae8473e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/h2</value>
      <webElementGuid>700abed8-0d39-481f-807b-1f7af7a8b9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'برنامج التوجيهي و الثانوي' or . = 'برنامج التوجيهي و الثانوي')]</value>
      <webElementGuid>ff8dc41a-1821-41f4-8049-702b930958f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
