<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_jjo</name>
   <tag></tag>
   <elementGuidId>01854439-663d-4a90-be21-ee59dcee6b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reply']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;jjo&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e9eb15ed-ddea-4025-83dc-0912a990a229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply</value>
      <webElementGuid>cd1adf7e-cd3f-41d9-9a04-d98e35a241a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-w-full tw-resize-none tw-rounded-[12px] tw-border-none tw-bg-[#EFEFEF] tw-px-[16px] tw-py-[8px] tw-pe-[50px] placeholder:tw-text-[14px] placeholder:tw-font-normal placeholder:tw-text-[#979797] focus-visible:!tw-outline focus-visible:!tw-outline-gray-300</value>
      <webElementGuid>8d716a78-0ab9-4346-ba33-627cda51b50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>f1019a02-a476-425b-97ae-361348a772d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4de0cc2e-f255-4e07-83b5-527f6d98c4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jjo</value>
      <webElementGuid>25c1ca29-0834-4a2b-9460-b1cf63bd416d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply&quot;)</value>
      <webElementGuid>708052e1-1f6c-4911-87b3-4717ae2f06e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reply']</value>
      <webElementGuid>b1f229bf-40d3-440e-b9d4-fd9b46488de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[7]/div[2]/div/textarea</value>
      <webElementGuid>ed825867-0de8-426b-976d-26f71eeb7e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التعليقات'])[2]/following::textarea[1]</value>
      <webElementGuid>35ba5988-dbef-4212-92c9-b875be6be845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اعجبني'])[1]/following::textarea[1]</value>
      <webElementGuid>a8baf38f-c56a-46df-a6ac-e339f11da4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linda al darabseh'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8c99983b-df71-4b8f-ab35-9f8e2356e245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ياربييييي'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5452b80f-0689-431c-a8d4-be13b639aed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jjo']/parent::*</value>
      <webElementGuid>9c11be21-0152-487b-9de1-ed6b82e1ef56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>f0eb62aa-3460-4fdf-a042-0dd46d9c402a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'reply' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'jjo' or . = 'jjo')]</value>
      <webElementGuid>ce36e538-92b1-4dff-87c4-806b83c65668</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
