<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_jj</name>
   <tag></tag>
   <elementGuidId>0637e596-b8b2-47fe-8d9c-5e1b3b07dd25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reply']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;jj&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>15012a33-5c8f-4f68-ab4a-48b03d943826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply</value>
      <webElementGuid>8455234a-8a5a-400d-b669-b3326c258e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-w-full tw-resize-none tw-rounded-[12px] tw-border-none tw-bg-[#EFEFEF] tw-px-[16px] tw-py-[8px] tw-pe-[50px] placeholder:tw-text-[14px] placeholder:tw-font-normal placeholder:tw-text-[#979797] focus-visible:!tw-outline focus-visible:!tw-outline-gray-300</value>
      <webElementGuid>922fb01c-b0b8-4a70-be56-ee68b9ae47b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>f3b6f3bb-8951-4fe0-8a6a-35c4bdb97fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a1658224-e1c1-4bda-bb39-63a16fc260e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jj</value>
      <webElementGuid>c76953af-7311-4d25-a9c1-8544e2ddefcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply&quot;)</value>
      <webElementGuid>243e6082-44f9-4625-aa6c-cf98dda50288</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reply']</value>
      <webElementGuid>14346ecc-0f81-4e86-973c-67a9ad5fa43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[7]/div[2]/div/textarea</value>
      <webElementGuid>38634737-b4da-4373-815f-03cfc674eedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التعليقات'])[2]/following::textarea[1]</value>
      <webElementGuid>8fe91496-7bae-44e0-b565-1d1ce6f96d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اعجبني'])[1]/following::textarea[1]</value>
      <webElementGuid>0395ff7e-787b-4f65-a172-d885c05fea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linda al darabseh'])[1]/preceding::textarea[1]</value>
      <webElementGuid>064e2416-5667-4b37-81a5-772dcfa9d5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ياربييييي'])[1]/preceding::textarea[1]</value>
      <webElementGuid>62ad8b02-15ee-40f4-8e3f-1c4e422ce55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jj']/parent::*</value>
      <webElementGuid>fe61fbe6-fd10-40d1-a792-6deeea71b445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>51b39c62-6cf8-47dc-abe2-4179433299bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'reply' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'jj' or . = 'jj')]</value>
      <webElementGuid>a7399eb6-3bb6-4af5-a89e-fb5c7f2428f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
