<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_j</name>
   <tag></tag>
   <elementGuidId>55e5e15e-699c-4726-85c8-15030dd23df4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reply</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='reply']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;j&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4276e5b3-3605-4f4d-8690-7727ed8e1d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply</value>
      <webElementGuid>8393db86-27e5-497f-ab8a-2b474b8adcc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-w-full tw-resize-none tw-rounded-[12px] tw-border-none tw-bg-[#EFEFEF] tw-px-[16px] tw-py-[8px] tw-pe-[50px] placeholder:tw-text-[14px] placeholder:tw-font-normal placeholder:tw-text-[#979797] focus-visible:!tw-outline focus-visible:!tw-outline-gray-300</value>
      <webElementGuid>d06f0b55-9fe2-4ccd-a2da-8253050831db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>396c798e-156d-4365-8601-838ddcb6a448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9298da8-c854-4190-b3f4-867be7f34500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>j</value>
      <webElementGuid>16c25376-cd08-475c-a7ee-0d7fdbeb63fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reply&quot;)</value>
      <webElementGuid>15ccc114-90e6-40f3-afcf-fed84c43897e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='reply']</value>
      <webElementGuid>f6185db9-b366-41d5-ac6f-4f8dc7668090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[7]/div[2]/div/textarea</value>
      <webElementGuid>af29015b-8d4b-49ba-8c5a-a25a24b76002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التعليقات'])[2]/following::textarea[1]</value>
      <webElementGuid>0686ab34-f6dc-48b5-82a5-93830a68e5dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اعجبني'])[1]/following::textarea[1]</value>
      <webElementGuid>98eb0e4b-e450-4fd2-8d5d-b6af234f97d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linda al darabseh'])[1]/preceding::textarea[1]</value>
      <webElementGuid>22f59240-67be-4c22-85f4-3fdbf396c77d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ياربييييي'])[1]/preceding::textarea[1]</value>
      <webElementGuid>acaa9308-52ba-4ad8-9b57-8ceb0d914813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='j']/parent::*</value>
      <webElementGuid>0c03cc8c-88d6-4d28-b3d4-2a3adfeb338a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/textarea</value>
      <webElementGuid>98abb78f-809c-4831-b69f-fe59055b5603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'reply' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'j' or . = 'j')]</value>
      <webElementGuid>9bdaa24a-7189-4459-b494-f6feb034321c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
