<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>184bcf13-761c-4d81-80cb-a9639bb3ea13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/section/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;قروب لعيون غصن غصنصن&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>eaff1969-9856-4353-90e4-4d83f6c0d0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-text-[16px] tw-m-0 tw-break-words tw-wrap-text</value>
      <webElementGuid>61163a32-3d70-40f8-90ad-d7afaa1b6e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>قروب لعيون غصن غصنصن</value>
      <webElementGuid>0516f41f-4403-4d3d-8461-f4394e550806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-my-[80px] tw-w-full&quot;]/div[@class=&quot;tw-mt-[64px] tw-px-[10px] lg:tw-px-[40px] xl:tw-px-[120px]  tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-between tw-gap-[24px]  md:tw-flex-row&quot;]/section[@class=&quot;tw-flex tw-w-full tw-shrink-0 tw-flex-col tw-items-start tw-justify-start tw-gap-[24px] lg:!tw-w-2/3&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center&quot;]/div[@class=&quot;tw-tab-content tw-w-full&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-center tw-justify-center tw-gap-[24px]&quot;]/div[@class=&quot;tw-h-fit tw-w-full tw-rounded-[12px] tw-border tw-bg-[#F9F9F9] !tw-p-[24px]&quot;]/div[@class=&quot;horizontal_card tw-my-[12px] tw-flex tw-min-h-[100px] tw-w-full tw-items-center tw-justify-between tw-overflow-hidden tw-rounded-[12px] tw-border tw-bg-[#FFFFFF] tw-px-[16px]&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-center tw-justify-center tw-gap-[16px]&quot;]/div[@class=&quot;tw-flex tw-h-full tw-w-full tw-cursor-pointer tw-items-center tw-justify-start tw-gap-[4px] tw-self-stretch md:tw-gap-[5px]&quot;]/div[@class=&quot;tw-flex tw-h-full tw-w-full tw-items-start tw-justify-start tw-gap-2 tw-p-[8px]&quot;]/div[@class=&quot;tw-overflow-hidden tw-leading-[24px]&quot;]/h2[@class=&quot;tw-text-[16px] tw-m-0 tw-break-words tw-wrap-text&quot;]</value>
      <webElementGuid>a4a1aafb-0de4-4551-9cea-27cf4c553a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/section/div[2]/div[2]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/h2</value>
      <webElementGuid>c524fb70-0b7a-4d0d-b15e-08f7a6164042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشاء مجموعة جديدة'])[1]/following::h2[1]</value>
      <webElementGuid>8d2772dd-9a77-4f9d-b200-9fdcf3fe7b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جروبات اخرى'])[1]/following::h2[1]</value>
      <webElementGuid>703dcd1a-a6bb-4e92-a5f3-5d354b196eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::h2[1]</value>
      <webElementGuid>789bc3be-4045-466d-a19c-e8f543859362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انضمام'])[6]/preceding::h2[1]</value>
      <webElementGuid>b47f395e-1172-4142-8b45-41c6e2b19b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='قروب لعيون غصن غصنصن']/parent::*</value>
      <webElementGuid>ed2547d5-d5b5-4296-93d5-c190a1fb36d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/div/div[2]/div/h2</value>
      <webElementGuid>def3a504-439b-49e0-8ada-36cf676c698d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'قروب لعيون غصن غصنصن' or . = 'قروب لعيون غصن غصنصن')]</value>
      <webElementGuid>610e01e5-f611-4d59-ad9b-7e673241df60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
