<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mohannad qa qajoo Close</name>
   <tag></tag>
   <elementGuidId>21edeca2-0d67-48fe-832b-708ea59e8877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:r2t:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;تعديل التعليقMohannad qa qajooحفظ التعديلClose&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0748fdd-4063-4ed1-9a16-06a67bae3c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>5b087491-780a-4e35-ab57-d85ed72b2eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r2t:</value>
      <webElementGuid>f1a4dc98-e472-421a-9397-4fa0ab4ef2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-:r2v:</value>
      <webElementGuid>2acbf5b9-b58f-4413-9843-316848f56d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-:r2u:</value>
      <webElementGuid>c94733f2-70f4-4a61-9fe8-d4c518cd1010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>7bcc3821-e7e4-4dc4-988a-9164ee6b3300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>rtl</value>
      <webElementGuid>52c3c4b3-d9b7-4e32-8b2e-327134440b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sm:max-w-[425px] tw-gap-[40px] tw-fixed tw-left-[50%] tw-top-[50%] tw-z-50 tw-grid tw-w-full tw-max-w-lg tw-translate-x-[-50%] tw-translate-y-[-50%] tw-gap-4 tw-rounded-[10px] tw-fixed tw-left-[50%] tw-top-[50%] tw-z-50 tw-grid tw-w-full tw-max-w-lg tw-translate-x-[-50%] tw-translate-y-[-50%] tw-gap-4 tw-rounded-[10px] tw-border tw-bg-white tw-p-6 tw-shadow-lg tw-duration-200r tw-bg-white tw-p-6 tw-shadow-lg tw-duration-200 tw-animate-in tw-fade-in-0 tw-zoom-in-95 tw-slide-in-from-left-1/2 tw-slide-in-from-top-[48%]</value>
      <webElementGuid>512501a0-211d-4a23-b3dc-ed2eee41dd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b8397ad9-1dae-4e1e-97d9-0ca132a15b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تعديل التعليقMohannad qa qajooحفظ التعديلClose</value>
      <webElementGuid>a75fa968-d712-4558-8517-4999f6a2a8eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2t:&quot;)</value>
      <webElementGuid>4332a988-e844-4615-be5d-947abe7c4cce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2t:']</value>
      <webElementGuid>eedd7cdb-f10b-4535-ac85-3fcbd8aa25c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحاتنا على مواقع التواصل الاجتماعي'])[1]/following::div[9]</value>
      <webElementGuid>e098c956-dff3-45d7-ab95-ccb2f31f09fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>6e9c2261-b5ef-4f26-8f12-3502ef49edce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-:r2t:' and (text() = 'تعديل التعليقMohannad qa qajooحفظ التعديلClose' or . = 'تعديل التعليقMohannad qa qajooحفظ التعديلClose')]</value>
      <webElementGuid>f79fe7d6-5754-42ac-91da-05a66e0f444d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
