<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submit-reply</name>
   <tag></tag>
   <elementGuidId>b94ce9aa-7349-4995-be12-8544aaef9dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[8]/div/div[2]/div[3]/div[2]/button/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;submit&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a34ea937-fadc-481d-9934-3072ca802734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a2a06161-a7aa-46a9-adcb-a68e1fadf958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>fd205c7e-4f26-45b4-8ae8-7c0b0428d87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>748cedf3-c363-462c-826f-e900e73845c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8dbf22be-9813-41db-ba51-3050bfaf161a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>60af0628-16da-42d7-891d-85cb71fc1df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a609759b-eac4-4f0f-9c32-4d1bfea313be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!tw-w-5 tw-bg-transparent ltr:tw-rotate-180   tw-cursor-pointer</value>
      <webElementGuid>924cd9e4-34f6-402b-bd82-358b937b2135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icons/shababeek/send_active.svg</value>
      <webElementGuid>82519dda-9033-4b9e-9ac4-93667318c90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-mb-5 tw-mt-20 tw-px-4 lg:tw-px-8 2xl:tw-px-32&quot;]/div[@class=&quot;tw-w-full lg:tw-flex lg:tw-flex-row-reverse lg:tw-justify-between&quot;]/div[@class=&quot;lg:tw-w-[57%]&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-[18px] lg:tw-gap-[24px]&quot;]/div[@class=&quot;tw-h-fit tw-w-full tw-rounded-[12px] tw-border tw-bg-[#F9F9F9] !tw-p-[24px]&quot;]/div[@class=&quot;tw-relative tw-mt-4 tw-flex tw-flex-col tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-mb-2 tw-flex tw-w-full tw-items-center tw-justify-start tw-gap-[4px]&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-overflow-hidden&quot;]/div[@class=&quot;tw-my-3 tw-flex tw-items-start tw-justify-start tw-gap-3&quot;]/div[@class=&quot;tw-relative tw-me-16 tw-w-full&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantGhost__8YgBv styles_buttonColorBlue__0VHnR tw-rounded-[10px] tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] tw-absolute tw-bottom-4 tw-end-4 tw-flex !tw-w-auto tw-max-w-[80px] tw-gap-2 !tw-p-0 !tw-text-[#1D428A] hover:!tw-bg-transparent&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center&quot;]/img[@class=&quot;!tw-w-5 tw-bg-transparent ltr:tw-rotate-180   tw-cursor-pointer&quot;]</value>
      <webElementGuid>4862fb7f-8c81-4de0-9f89-a43fbb3bee3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[8]/div/div[2]/div[3]/div[2]/button/div/img</value>
      <webElementGuid>943bbe28-c22d-426c-8d6e-694d9e7f07eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='submit'])[2]</value>
      <webElementGuid>96928a9d-b560-41a5-ba77-2379c9152bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button/div/img</value>
      <webElementGuid>d19a5650-c1a0-4903-98bc-cf0e7f27b121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'submit' and @src = '/icons/shababeek/send_active.svg']</value>
      <webElementGuid>c594a2ec-cd86-4239-8722-cf40973bbb64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
