<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_</name>
   <tag></tag>
   <elementGuidId>1bd97a71-2eb0-4a36-b16a-0abf91ea5a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/form/div/div[2]/div[4]/div/label/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;اضف صورة / فيديو&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ac3b5186-6427-43e8-860d-db4ed9642d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اضف صورة / فيديو</value>
      <webElementGuid>5a0401cf-4aa3-403e-81c8-9b96da2d8e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-mb-5 tw-mt-20 tw-px-4 lg:tw-px-8 2xl:tw-px-32&quot;]/div[@class=&quot;tw-w-full lg:tw-flex lg:tw-flex-row-reverse lg:tw-justify-between&quot;]/div[@class=&quot;lg:tw-w-[57%]&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-[18px] lg:tw-gap-[24px]&quot;]/form[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-h-fit tw-w-full tw-rounded-[12px] tw-bg-[#F9F9F9] tw-shadow&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-start tw-justify-start tw-gap-[12px] tw-bg-white tw-p-[18px]&quot;]/div[@class=&quot;tw-flex tw-h-fit tw-w-full tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-relative tw-flex tw-flex-col tw-flex-wrap tw-items-center&quot;]/label[@class=&quot;focus:tw-shadow-outline-blue tw-duration-400 tw-flex tw-cursor-pointer tw-items-center tw-justify-center tw-rounded-full tw-border tw-px-8 tw-py-2 tw-text-[#1A428A] hover:tw-bg-blue-50 focus:tw-outline-none&quot;]/p[1]</value>
      <webElementGuid>b00ef7fb-db4f-4320-aeb1-bcd2d50d0b62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/form/div/div[2]/div[4]/div/label/p</value>
      <webElementGuid>e80f10f4-0fa2-4f1e-82ba-6f504c2e72cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انضمام'])[10]/following::p[2]</value>
      <webElementGuid>03b75ae4-661c-4d09-a1c9-668d0a2f902a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جيل 2008'])[2]/following::p[2]</value>
      <webElementGuid>61125382-c06c-4751-a554-e4b7027f74ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشر'])[1]/preceding::p[1]</value>
      <webElementGuid>709e98db-3956-4f62-860c-24ad24722e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تذييل جو أكاديمي'])[1]/preceding::p[2]</value>
      <webElementGuid>e6597a17-91e6-4ae7-8897-42beea7b8d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اضف صورة / فيديو']/parent::*</value>
      <webElementGuid>cfe8a776-3bd3-44c5-80e6-2b4bc7b25869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/p</value>
      <webElementGuid>0e8b4bfd-14c5-421e-b409-3bff6d018c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'اضف صورة / فيديو' or . = 'اضف صورة / فيديو')]</value>
      <webElementGuid>e817175f-0564-4684-8157-6dc265147207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
