<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>f546c6dc-5743-450e-a4c1-8d76b703de88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div/div[2]/div/section/div[2]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;الملفات icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eaefc578-879e-4e89-8e39-77fa164feeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> tw-relative tw-flex tw-transform tw-cursor-pointer tw-flex-col tw-items-center tw-justify-center tw-gap-4 tw-rounded-xl tw-bg-[#fff] tw-p-4 tw-transition-all tw-duration-300 tw-ease-in-out hover:tw-scale-105 hover:!tw-shadow-lg </value>
      <webElementGuid>9da743b7-1bfc-444c-a6e9-cd66a4e44576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/files/category/tawjihi-2007</value>
      <webElementGuid>ebd0936d-75e1-470b-9b64-9c3c95bdfe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الملفات</value>
      <webElementGuid>189e18dc-7851-4645-81a0-4c81ebac3b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-w-full&quot;]/div[@class=&quot;tw-relative tw-flex tw-w-full&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-relative !tw-w-full tw-mx-auto tw-w-full lg:tw-w-[calc(100vw-280px)] !tw-overflow-hidden&quot;]/div[1]/section[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-center tw-justify-center tw-gap-12 tw-bg-[#F9F9F9] tw-p-2 md:!tw-p-5 lg:!tw-p-10&quot;]/div[@class=&quot;tw-grid tw-w-full tw-grid-cols-2 tw-gap-4 md:tw-grid-cols-3 lg:tw-grid-cols-4&quot;]/a[@class=&quot;tw-relative tw-flex tw-transform tw-cursor-pointer tw-flex-col tw-items-center tw-justify-center tw-gap-4 tw-rounded-xl tw-bg-[#fff] tw-p-4 tw-transition-all tw-duration-300 tw-ease-in-out hover:tw-scale-105 hover:!tw-shadow-lg&quot;]</value>
      <webElementGuid>e62a97d4-b72e-4fbf-8113-bebaeafd12ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/div/section/div[2]/a[3]</value>
      <webElementGuid>bc1c1014-87f5-4646-ac7a-b7363e185f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تكميلي 2006'])[1]/following::a[3]</value>
      <webElementGuid>8d36e1bc-96d3-45c7-8b43-84d9cad5577a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='توجيهي 2009'])[1]/following::a[3]</value>
      <webElementGuid>6bd1f699-137d-46c0-aa66-302ddf573f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمات جو اكاديمي ل جيل 2007'])[1]/preceding::a[9]</value>
      <webElementGuid>bac77f6c-d831-4fb0-b02f-e1fa83e7aaf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الساعات المكتبية 2007'])[1]/preceding::a[9]</value>
      <webElementGuid>6bc09534-fadc-4da4-ab69-ed5943c4399c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/files/category/tawjihi-2007')]</value>
      <webElementGuid>f6c20268-a5ab-4573-9b51-79b99914cd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]</value>
      <webElementGuid>9c35bd6a-4c4c-4988-a12b-07c244d2afaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/files/category/tawjihi-2007' and (text() = 'الملفات' or . = 'الملفات')]</value>
      <webElementGuid>26fe7ef7-2688-4a38-9be6-e5aa8e49b4a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
