<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>c789d554-1cd2-4169-9733-7c38e7724dde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;حذف حذف&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21cd1a3b-30a5-4978-bf54-6d16f6fd6b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantGhost__8YgBv styles_buttonColorBlue__0VHnR tw-rounded-full tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] tw-flex tw-w-full tw-min-w-[80px] !tw-justify-start tw-gap-3 tw-rounded-none !tw-text-black</value>
      <webElementGuid>abd5e142-44a2-46d5-a7c6-b5c18d387b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e407c621-ccc1-4736-8a47-d3452f60f549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حذف</value>
      <webElementGuid>82eca408-c1aa-4667-b18e-5cc7d780db57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r37:&quot;)/div[@class=&quot;tw-relative tw-flex tw-cursor-default tw-select-none tw-items-center tw-rounded-sm tw-px-2 tw-py-1.5 tw-text-sm tw-outline-none tw-transition-colors focus:tw-bg-slate-100 focus:tw-text-slate-900 data-[disabled]:tw-pointer-events-none data-[disabled]:tw-opacity-50 dark:focus:tw-bg-slate-800 dark:focus:tw-text-slate-50&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantGhost__8YgBv styles_buttonColorBlue__0VHnR tw-rounded-full tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] tw-flex tw-w-full tw-min-w-[80px] !tw-justify-start tw-gap-3 tw-rounded-none !tw-text-black&quot;]</value>
      <webElementGuid>8b8a3cb5-de9f-4795-a61b-693bc86b0097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>fec2c09d-1019-4614-823f-aa9e7bc63d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r37:']/div[3]/button</value>
      <webElementGuid>d0a71ca3-67b9-4d1e-b2c0-5368b5ee89fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تعديل'])[1]/following::button[1]</value>
      <webElementGuid>0a9de64b-9954-4e7e-a9c8-f317a8878f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تم التحديث بنجاح'])[1]/following::button[3]</value>
      <webElementGuid>775dd64c-ea98-420c-9a39-b2ed9a7386ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حذف']/parent::*</value>
      <webElementGuid>f4acab6d-0f2e-43f3-8c10-b4c80354f5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button</value>
      <webElementGuid>f0c98f92-ca9e-4a13-ab7e-e217849a920f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'حذف' or . = 'حذف')]</value>
      <webElementGuid>1e69f58f-2310-42f3-9ada-0fedb618e0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
