<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>0e681bd6-9f30-48c3-8200-1e64304cd334</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>d08e03a2-bf20-4845-bd17-4b29cdee07dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px] </value>
      <webElementGuid>d4b4a09b-54e4-4de7-bda4-98cfa289202d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي</value>
      <webElementGuid>04c88745-6441-4680-983f-28da6d5aeafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/h2[@class=&quot;semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px]&quot;]</value>
      <webElementGuid>42c603f6-3cc5-4049-8c1b-5ddd15d49d24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      <webElementGuid>6b06b9d5-9aed-4da3-98fe-a9e0b449364d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر البرنامج الذي تفضل التصفح عبره، حتى تمكننا من خدمتك بأفضل طريقة ممكنة'])[1]/following::h2[1]</value>
      <webElementGuid>4f13ae6f-6d14-4700-99b2-5f66608f2630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جو اكاديمي | جيل عربي متمكن'])[1]/following::h2[2]</value>
      <webElementGuid>e14e43a2-9aa1-4a54-b81a-6aedb3dda9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الجامعات و الكليات'])[1]/preceding::h2[1]</value>
      <webElementGuid>3eb2e81f-06ca-469e-8520-b425ec2f97d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الصفوف الاساسية'])[1]/preceding::h2[2]</value>
      <webElementGuid>84c76ad2-9e3a-4c50-9c9e-61a9573bb4c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='برنامج التوجيهي و الثانوي']/parent::*</value>
      <webElementGuid>dacf0375-dbb7-4000-ab0a-2d693cfe872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/h2</value>
      <webElementGuid>296a9b67-8385-4d61-ab0b-c5313f1f6144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'برنامج التوجيهي و الثانوي' or . = 'برنامج التوجيهي و الثانوي')]</value>
      <webElementGuid>9b8a6681-40a2-4115-98ae-d45254774fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
