<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>like</name>
   <tag></tag>
   <elementGuidId>0e9dee50-5095-48e3-8e06-1837a40b6a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[6]/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;اعجبني&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2310b00f-158b-419e-92e5-d1b42d863d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-px-1 tw-pt-1 tw-text-sm tw-font-bold tw-duration-75 tw-ease-in-out md:tw-text-base tw-text-[#1A428A] </value>
      <webElementGuid>cf87ad64-6a52-4cba-90b0-67605a602569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>اعجبني</value>
      <webElementGuid>a7beaf8a-482e-4495-95fd-90855e262e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-mb-5 tw-mt-20 tw-px-4 lg:tw-px-8 2xl:tw-px-32&quot;]/div[@class=&quot;tw-w-full lg:tw-flex lg:tw-flex-row-reverse lg:tw-justify-between&quot;]/div[@class=&quot;lg:tw-w-[57%]&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-[18px] lg:tw-gap-[24px]&quot;]/div[@class=&quot;tw-h-fit tw-w-full tw-rounded-[12px] tw-border tw-bg-[#F9F9F9] !tw-p-[24px]&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-start tw-gap-2&quot;]/div[@class=&quot;tw-relative tw-flex tw-cursor-pointer tw-items-center tw-justify-center&quot;]/div[@class=&quot;tw-flex tw-items-center tw-justify-center tw-p-1&quot;]/span[@class=&quot;tw-px-1 tw-pt-1 tw-text-sm tw-font-bold tw-duration-75 tw-ease-in-out md:tw-text-base tw-text-[#1A428A]&quot;]</value>
      <webElementGuid>9195c580-fe36-422e-a8d7-1f169cde013e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[6]/div/div/div/span</value>
      <webElementGuid>2001b2e6-1a46-45ae-ad8b-cd8f538e9bf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التعليقات'])[1]/following::span[1]</value>
      <webElementGuid>ea435e7a-0421-4ad8-9477-a0bf2a415aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اعجاب'])[1]/following::span[3]</value>
      <webElementGuid>d70c9c25-bc64-408b-a5f4-880962cf1497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='التعليقات'])[2]/preceding::span[1]</value>
      <webElementGuid>29e7a924-fe81-4b14-8cc4-e3ad69667035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohannad qa qa'])[2]/preceding::span[2]</value>
      <webElementGuid>95d95d96-fe0d-4fc8-979c-9307b71756c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='اعجبني']/parent::*</value>
      <webElementGuid>10f27aa0-0ae2-4154-9d79-dae92c6a9d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/span</value>
      <webElementGuid>cc7d9609-a1e8-4014-aafe-f681d66918b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'اعجبني' or . = 'اعجبني')]</value>
      <webElementGuid>444221d0-c8a1-4504-8a9d-20cc1699ca15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
