<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_j_1</name>
   <tag></tag>
   <elementGuidId>cb828d46-bd24-4d32-ab16-032ca300d18f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='reply'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.tw-relative.tw-me-16.tw-w-full > div.tw-h-full.tw-w-full > #reply</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;j&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1e0d63e8-9454-4573-8fdc-b4d100dd33c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reply</value>
      <webElementGuid>9f9875d6-8088-4652-a553-a72977422426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-w-full tw-resize-none tw-rounded-[12px] tw-border-none tw-bg-[#EFEFEF] tw-px-[16px] tw-py-[8px] tw-pe-[50px] placeholder:tw-text-[14px] placeholder:tw-font-normal placeholder:tw-text-[#979797] focus-visible:!tw-outline focus-visible:!tw-outline-gray-300</value>
      <webElementGuid>fd9185d7-68cd-412e-8fa2-fdae0e66d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>60a001df-8f08-4c86-ba1b-9305b188c6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f29fb042-2c82-4a32-a158-146c2c8ad105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>j</value>
      <webElementGuid>0d951c27-362e-4497-acb7-96c48de528e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;tw-flex tw-min-h-screen tw-w-full tw-flex-col tw-justify-between tw-bg-[#F9F9F9]&quot;]/div[@class=&quot;tw-mb-5 tw-mt-20 tw-px-4 lg:tw-px-8 2xl:tw-px-32&quot;]/div[@class=&quot;tw-w-full lg:tw-flex lg:tw-flex-row-reverse lg:tw-justify-between&quot;]/div[@class=&quot;lg:tw-w-[57%]&quot;]/div[@class=&quot;tw-flex tw-flex-col tw-items-center tw-justify-center tw-gap-[18px] lg:tw-gap-[24px]&quot;]/div[@class=&quot;tw-h-fit tw-w-full tw-rounded-[12px] tw-border tw-bg-[#F9F9F9] !tw-p-[24px]&quot;]/div[@class=&quot;tw-relative tw-mt-4 tw-flex tw-flex-col tw-items-center tw-justify-between&quot;]/div[@class=&quot;tw-mb-2 tw-flex tw-w-full tw-items-center tw-justify-start tw-gap-[4px]&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-overflow-hidden&quot;]/div[@class=&quot;tw-my-3 tw-flex tw-items-start tw-justify-start tw-gap-3&quot;]/div[@class=&quot;tw-relative tw-me-16 tw-w-full&quot;]/div[@class=&quot;tw-h-full tw-w-full&quot;]/textarea[@id=&quot;reply&quot;]</value>
      <webElementGuid>0b9f0af3-7da0-4259-9f53-b787b429dd9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='reply'])[2]</value>
      <webElementGuid>b90c1e39-034e-4ec0-82e0-1ebf13160909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div[2]/div[2]/div/div/div[8]/div/div[2]/div[3]/div[2]/div/textarea</value>
      <webElementGuid>9e349563-ad5b-4c3b-af36-a33277b9025d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='joj'])[1]/following::textarea[1]</value>
      <webElementGuid>0d354a51-74ac-4d67-af49-3b25c238eba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohannad qa qa'])[2]/following::textarea[1]</value>
      <webElementGuid>75d564e3-c21f-4985-a35b-21d2aefebf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohannad qa qa'])[3]/preceding::textarea[1]</value>
      <webElementGuid>a8b668bd-2d59-4d6d-bfb7-8fa9ad16afd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jo'])[2]/preceding::textarea[1]</value>
      <webElementGuid>2ad109a3-60bc-44e2-9e1d-d01e8383939d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='j']/parent::*</value>
      <webElementGuid>e5438918-a458-4663-bd06-4bb9fdbf98f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/textarea</value>
      <webElementGuid>3c2dc66d-1516-4e5b-ba1d-895b3f94c19a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'reply' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'j' or . = 'j')]</value>
      <webElementGuid>221e22cc-9730-450c-b5cd-d2b62269ed47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
