<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close--ads</name>
   <tag></tag>
   <elementGuidId>f11eb59e-8eb1-4f05-a1fb-80d79adc36ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:ri:']/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ri-close-line.tw-text-3xl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>6c41d124-b06c-43f1-9bb9-7d1b50039a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-close-line tw-text-3xl</value>
      <webElementGuid>47bc4c77-58dd-4290-ab93-7325b87736d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:ri:&quot;)/div[@class=&quot;tw-absolute tw-left-2 tw-top-2 tw-flex tw-justify-center tw-items-center tw-h-12 tw-w-12 tw-font-extrabold tw-bg-white tw-shadow-md tw-rounded-full tw-text-[#262d3e] tw-cursor-pointer&quot;]/i[@class=&quot;ri-close-line tw-text-3xl&quot;]</value>
      <webElementGuid>a7a69239-8bb5-4c66-84d2-176a432b4c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ri:']/div/i</value>
      <webElementGuid>c6ab270f-93f8-49a0-ab8f-b2a2a43fa6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/i</value>
      <webElementGuid>906c69df-6de5-4396-aaa0-ad02b92d4e9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
