<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_</name>
   <tag></tag>
   <elementGuidId>a41df67c-f306-44cb-9bbf-5540be9167bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;اذهب الى  برنامج التوجيهي و الثانوي | جو اكاديمي&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>550adf89-34bf-4c85-9a24-fa9903aaea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px] </value>
      <webElementGuid>f9485568-2662-4c01-ba5e-f4953f2a3b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>برنامج التوجيهي و الثانوي</value>
      <webElementGuid>6d1cf300-54dd-428e-983a-d7dafe58a817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/section[1]/div[@class=&quot;tw-mt-2 tw-flex tw-flex-wrap tw-justify-center tw-gap-2 md:tw-gap-4 md:tw-p-4&quot;]/a[1]/div[@class=&quot;tw-relative  tw-flex tw-h-[214px] tw-w-[151px] tw-flex-col tw-items-center tw-justify-center  tw-rounded-lg  tw-duration-500 hover:tw--translate-y-6 max-sm:tw-h-[214px] max-sm:tw-w-[151px] md:tw-h-[391px] md:tw-w-[278px] tw-bg-[#0D2755]&quot;]/h2[@class=&quot;semi-bold tw-mt-5 tw-px-14 tw-text-center tw-leading-normal tw-text-white max-sm:tw-mt-0 max-sm:tw-px-5 max-sm:tw-text-base md:tw-text-[24px]&quot;]</value>
      <webElementGuid>fc4078fc-0ec9-44f3-8b97-2bf8a887b36e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/section/div[2]/a/div/h2</value>
      <webElementGuid>d549fe4e-977f-44b2-a4e4-1e7b57454f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اختر البرنامج الذي تفضل التصفح عبره، حتى تمكننا من خدمتك بأفضل طريقة ممكنة'])[1]/following::h2[1]</value>
      <webElementGuid>7a13f006-aa21-4359-8a91-602550f60e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جو اكاديمي | جيل عربي متمكن'])[1]/following::h2[2]</value>
      <webElementGuid>aeda3695-3a89-4288-b9df-96d6deb80df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الجامعات و الكليات'])[1]/preceding::h2[1]</value>
      <webElementGuid>7aa01f5d-5a38-4a45-86cb-284ae756fcbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='برنامج الصفوف الاساسية'])[1]/preceding::h2[2]</value>
      <webElementGuid>87f2d2df-c899-4df7-b2f4-ac91eb22cec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='برنامج التوجيهي و الثانوي']/parent::*</value>
      <webElementGuid>92a44b1f-d169-4675-8a85-d155caf6f58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/h2</value>
      <webElementGuid>a5cf99d7-6687-46ae-a1d3-d537e323b7eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'برنامج التوجيهي و الثانوي' or . = 'برنامج التوجيهي و الثانوي')]</value>
      <webElementGuid>a88033ff-202d-4322-ac02-2e385020aa20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
