<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_j</name>
   <tag></tag>
   <elementGuidId>968a814a-fb4d-4e73-99d7-039205bc8913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//textarea[@id='description'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;ماذا يخطر في بالك ؟&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6ec6c5d8-5c8f-48a8-a3e8-20515e69b7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>1cc7d304-c831-4369-9d5e-a9e16d6fef8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-min-h-12 tw-p-3 tw-h-auto tw-w-full tw-resize-none tw-overflow-auto tw-rounded-xl tw-border tw-border-gray-200 tw-p-4 tw-outline-none placeholder:tw-text-[#979797]</value>
      <webElementGuid>2af0ebba-301c-4860-9dc6-0abe732d387d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ماذا يخطر في بالك ؟</value>
      <webElementGuid>215f564f-705c-4a3e-8029-fbe45a48a5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>97a9e266-f8fb-45af-aca8-6503cf476969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>j</value>
      <webElementGuid>ab22a294-1f11-423f-a0d2-577950a770ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2v:&quot;)/div[@class=&quot;tw-max-h-[70vh] tw-overflow-auto&quot;]/div[@class=&quot;tw-flex tw-w-full tw-flex-col tw-items-start tw-justify-start tw-gap-[12px] tw-px-5&quot;]/div[@class=&quot;tw-h-full tw-w-full&quot;]/textarea[@id=&quot;description&quot;]</value>
      <webElementGuid>c0bba403-a135-4583-8f64-1d77744b43df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//textarea[@id='description'])[2]</value>
      <webElementGuid>22866a2f-3fac-4a46-a10c-7269f2d603ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2v:']/div/div/div[2]/textarea</value>
      <webElementGuid>af9b4688-2c76-433f-898b-ce8ae4bcc0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='٣٠ نوفمبر ٢٠٢٤ ١٧:٤٦'])[2]/following::textarea[1]</value>
      <webElementGuid>c8aaf3f0-652f-474c-a507-19e454f6cf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mohannad qa qa'])[2]/following::textarea[1]</value>
      <webElementGuid>fb5dad23-3885-4b99-bbb1-24b4aa22fc50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اضافة الى منشورك'])[1]/preceding::textarea[1]</value>
      <webElementGuid>38ea4584-15d0-40b8-9ef9-606cd4de6467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='انشر'])[2]/preceding::textarea[1]</value>
      <webElementGuid>9ffa7093-6764-43d3-88a6-95c92f9a0fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='j']/parent::*</value>
      <webElementGuid>0e01bf79-d48c-4ef8-ab44-715c2052289f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>58982076-c4d7-4b87-8352-64ccdee455d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'description' and @placeholder = 'ماذا يخطر في بالك ؟' and (text() = 'j' or . = 'j')]</value>
      <webElementGuid>0aaebfff-73cd-48ea-866f-ce8ca4f71141</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
