<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DELET-POST</name>
   <tag></tag>
   <elementGuidId>d2ceea42-4639-4175-bba4-b2de2c209a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'حذف' or . = 'حذف')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;حذف&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac6cdb92-c291-45ae-ad99-9f424595b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantOutline__gf_i8 styles_buttonColorBlue__0VHnR tw-rounded-full tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] !tw-w-[100px]</value>
      <webElementGuid>3fb7d6a6-8baa-464c-83f5-13b167c28fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>58074e58-6249-415e-a999-b1ac8b9589b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>حذف</value>
      <webElementGuid>4962878d-d4ae-42d4-b48b-443f5b889f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r2v:&quot;)/div[@class=&quot;tw-flex tw-flex-col tw-items-start tw-justify-center tw-gap-5&quot;]/div[@class=&quot;tw-flex tw-w-full tw-items-center tw-justify-end tw-gap-2&quot;]/button[@class=&quot;tw-max-w-full tw-w-full tw-transition tw-ease-in-out tw-duration-150 tw-font-bold tw-flex tw-items-center tw-justify-center tw-transition tw-ease-in-out tw-duration-150 styles_buttonVariantOutline__gf_i8 styles_buttonColorBlue__0VHnR tw-rounded-full tw-cursor-pointer tw-text-[14px] tw-py-[5px] tw-px-[10px] !tw-w-[100px]&quot;]</value>
      <webElementGuid>bbbf25f8-795d-41ae-b233-ef016da1c00f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>a2178820-01dc-41ee-8a6b-0309fb0075e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:r2v:']/div/div/button[2]</value>
      <webElementGuid>641412f3-9b22-4f08-80da-640318257c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الغاء'])[1]/following::button[1]</value>
      <webElementGuid>f085676d-d910-4fa0-b5c2-0de341fd671f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='سيتم حذف التعليق'])[1]/following::button[2]</value>
      <webElementGuid>f70ac2e3-ce18-4fea-97f3-db38f08e9d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::button[1]</value>
      <webElementGuid>4dd4c2ea-4373-4b85-b111-9e0e5faa0e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='حذف']/parent::*</value>
      <webElementGuid>0442b558-7912-4949-bf9f-5334a8dd543c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>68819489-324a-4bd2-acf9-09c0863f6796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'حذف' or . = 'حذف')]</value>
      <webElementGuid>5874b27d-0a8f-47ce-be1d-bffbf153a933</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
